spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vanessaandrandrin@gmail.com
    password: xeswbvtvdbpxkelr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

