server:
  port: 9195
cloud:
  aws:
    credentials:
      access-key: YOUR_ACCESS_KEY
      secret-key: YOUR_SECRET_KEY
    region:
     static: eu-central-1
    stack:
      auto: false
application:
  bucket:
    name: upload-download-file-aws
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 10MB

